### PR TITLE
intel-compute-runtime: Get patch from the repo, no need to copy it locally

### PR DESCRIPTION
**Pull request by ArchangeGabriel**
We still need to figure out dependencies properly before pushing.

### CODE REVIEW

**Comment by JacekDanecki** [comment]
@ArchangeGabriel What dependency issues do you observe?

**Comment by ArchangeGabriel** [comment]
Well installing just `intel-compute-runtime` like this and trying to start `darktable` resulted in a failure to compile OpenCL kernels. I’ve then added `intel-graphics-compiler`, went further but this time it even crashed Darktable. Finally I installed `intel-opencl-clang` and everything went fine. Note that I already had `intel-gmmlib` installed on my system, and I guess it is required too. But after that I could remove `intel-graphics-compiler` and `intel-opencl-clang` since Darktable caches the compiled kernels. Thus we should go for `optdepends` required to compile kernels I think.

So they are several questions arising. What is strictly required at runtime for `intel-compute-runtime`? What is required to compile OpenCL kernel for Neo? Is `intel-graphics-compiler` of any use without `intel-opencl-clang` (if not it should depend on it, not the case with the current PKGBUILD)? Where is `intel-gmmlib` required in all those scenarios?

**Comment by jdanecki** [comment]
At this moment intel-compute-runtime (Neo) requires packages:
- intel-graphics-compiler, intel-opencl-clang with llvm/clang
- intel-gmmlib
to work correctly for all scenarios.
As you can see [here](https://github.com/intel/compute-runtime/blob/master/runtime/compiler_interface/compiler_interface.cpp#L340) Neo loads igc and fcl library. opencl-clang is loaded later by compiler stack.
gmmlib is loaded by Neo [here](https://github.com/intel/compute-runtime/blob/master/runtime/gmm_helper/gmm_interface.cpp#L20)
To compile OpenCL kernel you need both intel-graphics-compiler and intel-opencl-clang, and llvm/clang libraries if you linked dynamic compilers libraries.
Current [PKGBUILD](https://github.com/dbermond/arch-packages/blob/master/intel-graphics-compiler/PKGBUILD#L10) should be corrected, as I'm not aware of any scenarios when you can use igc without opencl-clang.
intel-gmmlib is required by Neo for memory management, and program GPU state and  execute opencl workloads. 
I hope I clarify few things, if not, please ask more.

**Comment by ArchangeGabriel** [comment]
Awesome, thanks. Will send new PRs to fix this.

**Comment by ArchangeGabriel** [comment]
@dbermond I’ve updated this PR directly in the end.

**Pull request merged**
